apiVersion: v1
kind: Service
metadata:
  name: transcendence-app
  namespace: transcendence
spec:
  selector:
    app: transcendence
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30007
  
